"""Prompt registry for LLM alias-dictionary generation.

Each registry entry is a dict mapping a *pass name* to a prompt string;
:func:`generate_alias_dict` makes one API call per pass and merges the
results. New schema domains (e.g. ``"environmental_microbiome"``) plug
in by adding a new top-level key; the strict CSV output contract is
appended automatically by :func:`generate_alias_dict`.
"""
from __future__ import annotations


OUTPUT_FORMAT_INSTRUCTIONS = (
    "\n\nOutput requirements (strict):\n"
    "1. Return ONLY a CSV block inside a ```csv fenced code block.\n"
    "2. The first line must be the header: field_name,source,is_numeric_field\n"
    "3. One alias per row. The `field_name` value must exactly match one of "
    "the standardized field names listed below.\n"
    "4. For numeric fields set `is_numeric_field` to `yes`; otherwise leave "
    "it empty.\n"
    "5. Do not include any prose, commentary, or additional text outside the "
    "code block."
)


ALIAS_DICT_PROMPTS: dict[str, dict[str, str]] = {
    "cancer_genomics": {
        "synonym": (
            "You are generating a column-name alias dictionary for a biomedical "
            "metadata schema harmonization system. The system uses text "
            "normalization (lowercasing, replacing non-alphanumeric characters "
            "with spaces) and both exact and fuzzy string matching to map "
            "real-world column names to standardized field names.\n\n"
            "For each standardized field below, generate 8-12 plausible "
            "alternative column names that might appear in real clinical or "
            "genomic datasets from hospitals, research consortia, or public "
            "repositories (e.g., TCGA, GDC, ICGC, UK Biobank, dbGaP, "
            "cBioPortal, REDCap exports).\n\n"
            "For each field, provide aliases in these categories:\n"
            "A. Direct synonyms (e.g., body_site -> anatomic_site, "
            "tumor_location, primary_site)\n"
            "B. ALL_CAPS / SCREAMING_SNAKE_CASE variants (e.g., body_site -> "
            "BODY_SITE, PRIMARY_SITE)\n"
            "C. Reversed word order (e.g., age_at_diagnosis -> diagnosis_age)\n"
            "D. With patient/pt/subject prefix (e.g., age_at_diagnosis -> "
            "patient_age_at_diagnosis, pt_age_dx)\n"
            "E. Dot-separated variants (e.g., age_at_diagnosis -> DIAGNOSIS.AGE)\n"
            "F. Singular/plural variants where applicable"
        ),
        "abbreviation": (
            "You are an expert in biomedical data management conventions. "
            "Clinical and genomic datasets use extensive abbreviations in column "
            "names. Generate abbreviated column name variants for each "
            "standardized field below.\n\n"
            "Common abbreviation patterns in clinical data columns:\n"
            "- treatment/therapy -> TX, tx, trt, trtmt, therap\n"
            "- diagnosis -> DX, dx, diag\n"
            "- prescription/medication -> RX, rx\n"
            "- radiation/radiotherapy -> XRT, xrt, RT, rad\n"
            "- chemotherapy -> CT, chemo, ctx\n"
            "- immunotherapy -> IO, immuno, ICI\n"
            "- surgery -> surg, sx\n"
            "- biopsy -> BX, bx\n"
            "- age -> AGE (often as prefix)\n"
            "- patient -> PT, pt, PAT, subj\n"
            "- number/count -> NUM, num, cnt, n\n"
            "- status -> STAT, stat, sts\n"
            "- history -> HX, hx, hist\n"
            "- metastasis -> MET, met, mets\n"
            "- procurement/collection -> proc, coll\n"
            "- sequencing -> SEQ, seq\n"
            "- specimen -> SPEC, spec, spcmn\n"
            "- duration -> DUR, dur\n"
            "- frequency -> FREQ, freq\n"
            "- dose/dosage -> DOSE, dos\n"
            "- death/deceased -> DTH\n"
            "- disease -> DIS, dis\n"
            "- cancer -> CA, ca\n"
            "- tumor/tumour -> TUM, tum\n"
            "- subtype -> SUBT\n"
            "- type -> TYP\n"
            "- location -> LOC, loc\n"
            "- sample -> SAMP, samp\n"
            "- year/years -> YR, yrs\n"
            "- days -> D, d\n\n"
            "For each standardized field, generate 5-10 abbreviated column names "
            "that combine these shorthand patterns. Focus on forms that would NOT "
            "be obvious to a general-purpose language model but ARE standard in "
            "clinical informatics.\n\n"
            "Examples of the expected pattern:\n"
            "- treatment_type -> TX_TYPE, TRT_TYPE, CHEMO_TX, IO_TX, XRT_TX, "
            "CYTOTOXIC_TX\n"
            "- age_at_diagnosis -> AGE_D, AGE_DX, AGE_AT_DX, DX_AGE\n"
            "- treatment_name -> TX_REG, CHEMO_REGIMEN, IO_DRUG\n"
            "- vital_status -> OS_STATUS, DFS_STATUS, PFS_STATUS, DSS_STATUS\n"
            "- body_site -> TUMOR_LOC, PRIMARY_LOC, ANATOMIC_LOC, BIOPSY_LOC"
        ),
        "value_encoded": (
            "You are generating column name aliases for biomedical schema "
            "harmonization.\n\n"
            "A critical pattern in real clinical datasets is VALUE-ENCODED "
            "BOOLEAN COLUMNS: instead of having one column (e.g., \"body_site\") "
            "with text values like \"brain\" or \"lung\", datasets often have "
            "separate boolean columns where the column NAME contains the specific "
            "value:\n"
            "  - DIAGNOSIS_CANCER_LOC_BRAIN (yes/no) -> maps to body_site\n"
            "  - DIAGNOSIS_CANCER_LOC_LUNG (yes/no) -> maps to body_site\n"
            "  - FATTY_LIVER_DISEASE (indicator) -> maps to disease\n"
            "  - CNS_DISEASE (indicator) -> maps to disease\n\n"
            "Similarly for treatments:\n"
            "  - ADJUVANT_CHEMO (boolean) -> treatment_name or treatment_type\n"
            "  - CARBOPLATIN (boolean) -> treatment_name\n"
            "  - HAD_SURGERY (boolean) -> treatment_type\n\n"
            "For each CATEGORICAL (non-numeric) standardized field below, "
            "generate 5-15 value-encoded boolean column names that a clinical "
            "dataset might use. Think about what specific values each field "
            "might hold, then create column names that embed those values.\n\n"
            "Guidelines:\n"
            "- For body_site: use anatomical locations (BRAIN, LUNG, LIVER, "
            "BONE, SKIN, LYMPH_NODE, OVARY, BREAST, etc.) with prefixes like "
            "DIAGNOSIS_CANCER_LOC_, METS_, TUMOR_LOC_, ANYTIME_CANCER_LOC_\n"
            "- For disease: use specific diseases as columns "
            "(FATTY_LIVER_DISEASE, CNS_DISEASE, EXTRANODAL_DISEASE, "
            "DIABETES_DIAGNOSIS_INDICATOR, HYPERTENSION_DIAGNOSIS)\n"
            "- For cancer_subtype: use classification systems "
            "(PAM50_SUBTYPE, CLAUDIN_SUBTYPE, HISTOLOGY_SUBTYPE, "
            "ADENOCARCINOMA_SUBTYPE, MOLECULAR_SUBTYPE, IHC_SUBTYPE)\n"
            "- For treatment_name: use drug/regimen names "
            "(CARBOPLATIN, CISPLATIN, PEMBROLIZUMAB, NIVOLUMAB, TRASTUZUMAB, "
            "FOLFOX, CAPECITABINE)\n"
            "- For treatment_type: use modality names "
            "(RADIATION_THERAPY, IMMUNOTHERAPY, CHEMOTHERAPY, TARGETED_THERAPY, "
            "HORMONE_THERAPY, ADJUVANT_CHEMO, NEOADJUVANT_CHEMOTHERAPY, "
            "ADJUVANT_RADIATION_THERAPY, ADC_THERAPY)\n"
            "- For sex: use sex-implying clinical columns "
            "(INCIDENTAL_PROSTATE_CANCER, CERVIX_SUV_RESULTS, OVARIAN_STATUS)\n"
            "- For ancestry/ancestry_details: use specific group columns "
            "(HISPANIC, AFRICAN_AMERICAN, CAUCASIAN, ASIAN)\n\n"
            "Only generate value-encoded aliases for fields where this pattern "
            "is plausible. Skip numeric fields and fields where value-encoding "
            "would not occur naturally (e.g., ontology term ID fields)."
        ),
        "composite": (
            "You are generating column name aliases for biomedical schema "
            "harmonization.\n\n"
            "Real clinical datasets frequently use COMPOSITE COLUMN NAMES that "
            "combine a base concept with temporal, clinical, or methodological "
            "context. These composite names map to the same standardized field.\n\n"
            "Common composition patterns:\n"
            "1. TEMPORAL PREFIX + CONCEPT:\n"
            "   - PRIOR_*, HISTORY_*, PREVIOUS_*, INITIAL_*, BASELINE_*\n"
            "   - POST_SAMPLE_*, PRE_SAMPLE_*, CURRENT_*, RECENT_*\n\n"
            "2. TREATMENT CONTEXT + CONCEPT:\n"
            "   - ADJUVANT_*, NEOADJUVANT_*, FIRST_LINE_*, SALVAGE_*\n"
            "   - MAINTENANCE_*, INDUCTION_*, CONCURRENT_*, CONSOLIDATION_*\n\n"
            "3. METHODOLOGICAL CONTEXT + CONCEPT:\n"
            "   - AGE_AT_* (AGE_AT_CHEMOTHERAPY_START -> treatment_start)\n"
            "   - *_PRIOR_TO_* (THERAPY_PRIOR_TO_DERIVATION -> treatment_status)\n"
            "   - *_AT_DX, *_AT_DIAGNOSIS, *_AT_COLLECTION\n\n"
            "4. LINE-OF-THERAPY PATTERNS:\n"
            "   - FIRST_LINE, SECOND_LINE, THIRD_LINE, FOURTH_LINE, FIFTH_LINE\n"
            "   - 1L_*, 2L_*, 3L_* (numbered line-of-therapy indicators)\n"
            "   - FIRST_LINE_MET_TX, FIRSTLINE_CHEMO_GROUP\n\n"
            "5. BOOLEAN HISTORY PATTERNS:\n"
            "   - HAD_*, RECEIVED_*, UNDERWENT_*, EXPOSED_TO_*\n"
            "   - PRIOR_*, HISTORY_OF_*, FAMILY_HISTORY_*\n\n"
            "For each standardized field, generate 5-10 composite column names "
            "that combine the field's core concept with these contextual "
            "patterns. Focus especially on treatment_* fields, which have the "
            "richest compositional patterns."
        ),
        "institutional": (
            "You are generating column name aliases for biomedical schema "
            "harmonization.\n\n"
            "Clinical datasets from different institutions and studies use unique "
            "naming conventions. Generate column name variants that reflect these "
            "real-world patterns.\n\n"
            "Common institutional/study prefix patterns:\n"
            "- PRD_ (patient-reported data or institutional prefix)\n"
            "- CRDB_ (clinical research database prefix)\n"
            "- MSK_ or MSKCC_ (Memorial Sloan Kettering)\n"
            "- TCGA_ (The Cancer Genome Atlas)\n"
            "- GDC_ (Genomic Data Commons)\n"
            "- NGS_ (next-generation sequencing context)\n"
            "- ICD_ or ICD_O_ (ICD coding context)\n"
            "- CLIN_ or PATH_ (clinical vs. pathological)\n"
            "- CURATED_* (harmonized/curated prefix)\n"
            "- CALC_* or DERIVED_* (calculated/derived field)\n"
            "- INFERRED_* (computationally inferred)\n"
            "- REPORTED_* or SELF_REPORTED_* (patient-reported)\n\n"
            "Common suffix and format patterns:\n"
            "- Suffixes: *_INDICATOR, *_STATUS, *_FLAG, *_YN, *_TRTYN\n"
            "- Measurement units embedded: AGE_IN_DAYS, AGE_YRS, "
            "AGE_IN_YEARS, DOSE_MG, DOSE_MG_DAY\n"
            "- Dot notation: CANCER.TYPE, DIAGNOSIS.AGE\n"
            "- Mixed separators: AGE-AT-DIAGNOSIS\n"
            "- _PATIENT or _SAMPLE suffix: TUMOR_SITE_PATIENT, TUMOR_SITE_SAMPLE\n"
            "- _CURATED or _CONDENSED suffix: TUMOR_SITE_CURATED, "
            "TUMOR_LOCATION_CONDENSED\n\n"
            "For each standardized field, generate 3-5 column names using "
            "institutional prefixes, unusual separators, embedded units, or "
            "study-specific conventions."
        ),
    },
}
