---
title: "EDA: Different corpus for matching"
author: "Sehyun Oh, Jason Hwee, Xiang Li"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Different corpus for matching}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    number_sections: yes
    toc: yes
    toc_depth: 4
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(comment = "#>", 
                      collapse = TRUE, 
                      message = FALSE, 
                      warning = FALSE)
```

```{r echo=FALSE}
suppressPackageStartupMessages({
    library(dplyr)
    library(readr)
})
```

```{r}
projDir <- "~/OmicsMLRepo/OmicsMLRepoHarmonizer"
trtDir <- file.path(projDir, "outputs/cbio_treatment_name")
```


# From curated terms only
```{r message=FALSE}
trt_match <- read_csv(file.path(trtDir, "trt_name_match_from_curated.csv"))

table(trt_match$match_level)
summary(trt_match$match_level)
```

# From comprehensive corpus
This dynamic enum node (NCIT:C1909) contains 313 out of 546 curated terms.
```{r cbio_trt_dynamic_enums}
url <- "https://docs.google.com/spreadsheets/d/16PrHHfhcOdWYZW81vtJbxFvHTvPsaDEttFjNJRuW-ik/edit?usp=sharing"
ss <- googledrive::as_id(url)

## Ontology term ID of the terms covered by the selected dynamic enum node
trt_name <- googlesheets4::read_sheet(ss, sheet = "treatment_name_0.5")
trt_name_covered <- trt_name %>% 
    filter(ontology_term_id == "NCIT:C1909") %>%
    select(original_covered) %>%
    unlist %>%
    strsplit(., ";") %>%
    unlist %>%
    as.character

trt_name_map <- read.csv(file.path(projDir, "data/cBioPortal_treatment_name_map.csv"))
trt_name_query <- trt_name_map %>%
    filter(curated_ontology_term_id %in% trt_name_covered)

write.csv(trt_name_query, file.path(projDir, "data/cBioPortal_treatment_name_map_for_largerCorpus.csv"))
```

```{r message=FALSE}
trt_match <- read_csv(file.path(trtDir, "trt_name_match_from_corpus.csv"))

table(trt_match$match_level)
summary(trt_match$match_level)
```



```{r message=FALSE}
disease_match <- readr::read_csv(file.path(harmonizationDir, "disease_top5.csv"))

table(disease_match$match_level)
```
